//@ sourceMappingURL=grid.map
// Generated by CoffeeScript 1.6.1
(function() {
  var App, CCanvas, EventedClass, Grid, GridCanvas, ObjectContainer, ObjectExtender, ObjectFactory, ObjectGeneric, ObjectMulti, ObjectTerrain, ObjectTransporter, extend,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    _this = this;

  extend = function(object, properties) {
    var key, val;
    for (key in properties) {
      val = properties[key];
      object[key] = val;
    }
    return object;
  };

  window.App = App = (function() {

    function App() {
      this.grid = new Grid();
      this.gridCanvas = new GridCanvas;
      this.CCanvas = new CCanvas;
      this.CCanvas.setCanvas('grid_canvas');
      this.gridCanvas.drawGridLines(this.CCanvas.getContext(), this.grid);
    }

    return App;

  })();

  Grid = (function() {

    function Grid() {
      this.lineColor = 'rgba(0,0,0,1)';
      this.cellColor = 'rgbc(255,255,255,1)';
      this.bgColor = 'rgbc(255,255,255,1)';
      this.width = 4;
      this.height = 4;
      this.cellSize = 80;
      this.gridObjects = {};
      this.init();
    }

    Grid.prototype.getRealWidth = function() {
      return this.width - 1;
    };

    Grid.prototype.getRealHeight = function() {
      return this.height - 1;
    };

    Grid.prototype.init = function() {
      var x, y, _i, _ref, _results;
      _results = [];
      for (x = _i = 0, _ref = this.getRealWidth(); 0 <= _ref ? _i <= _ref : _i >= _ref; x = 0 <= _ref ? ++_i : --_i) {
        _results.push((function() {
          var _j, _ref1, _results1;
          _results1 = [];
          for (y = _j = 0, _ref1 = this.getRealHeight(); 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
            this.gridObjects["" + x + "," + y] = new ObjectContainer(new ObjectTerrain);
            this.gridObjects["" + x + "," + y].setX(x);
            _results1.push(this.gridObjects["" + x + "," + y].setY(y));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    Grid.prototype.setWidth = function(width) {
      this.width = width;
      return this.setWidthPx(this.width * this.cellSize);
    };

    Grid.prototype.setHeight = function(height) {
      this.height = height;
    };

    Grid.prototype.getWidthPx = function() {
      return this.width * this.cellSize;
    };

    Grid.prototype.getHeightPx = function() {
      return this.height * this.cellSize;
    };

    Grid.prototype.setCellSize = function(cellSize) {
      this.cellSize = cellSize;
    };

    Grid.prototype.setCellColor = function(cellColor) {
      this.cellColor = cellColor;
    };

    Grid.prototype.setBgColor = function(bgColor) {
      this.bgColor = bgColor;
    };

    Grid.prototype.getGridObjects = function() {
      return this.gridObjects;
    };

    Grid.prototype.scaleUp = function() {
      window.gApp.grid.cellSize = window.gApp.grid.cellSize / 2;
      window.gApp.gridCanvas.redrawAfterScale = true;
      return window.gApp.gridCanvas.updateCanvas(window.gApp.grid.gridObjects);
    };

    Grid.prototype.scaleDown = function() {
      window.gApp.grid.cellSize = window.gApp.grid.cellSize * 2;
      window.gApp.gridCanvas.redrawAfterScale = true;
      return window.gApp.gridCanvas.updateCanvas(window.gApp.grid.gridObjects);
    };

    Grid.prototype.updateCellContainer = function(cellX, cellY, data) {
      var checkObj, h, i, largeObjectH, largeObjectW, largeObjectX, largeObjectY, updateObjects, w, _i, _j, _k, _len, _ref, _ref1, _ref2;
      updateObjects = false;
      if (data.type === 'destroy') {
        checkObj = this.gridObjects["" + cellX + "," + cellY].object.content[0];
        if (checkObj.type === 'Extender' || checkObj.size.h > 1 || checkObj.size.w > 1) {
          if (checkObj.type === 'Extender') {
            largeObjectX = this.gridObjects["" + cellX + "," + cellY].object.content[0].belongsTo[0];
            largeObjectY = this.gridObjects["" + cellX + "," + cellY].object.content[0].belongsTo[1];
          } else {
            largeObjectY = cellY;
            largeObjectX = cellX;
          }
          largeObjectW = this.gridObjects["" + largeObjectX + "," + largeObjectY].object.content[0].size.w;
          largeObjectH = this.gridObjects["" + largeObjectX + "," + largeObjectY].object.content[0].size.h;
          for (w = _i = largeObjectX, _ref = largeObjectX + largeObjectW - 1; largeObjectX <= _ref ? _i <= _ref : _i >= _ref; w = largeObjectX <= _ref ? ++_i : --_i) {
            for (h = _j = largeObjectY, _ref1 = largeObjectY + largeObjectH - 1; largeObjectY <= _ref1 ? _j <= _ref1 : _j >= _ref1; h = largeObjectY <= _ref1 ? ++_j : --_j) {
              updateObjects["" + w + "," + h] = {};
            }
          }
        }
      } else if (data.size != null) {
        updateObjects = this.checkObjectBuild(data, this.gridObjects["" + cellX + "," + cellY]);
      } else {
        console.log('wrong size data for cell update?');
        return;
      }
      console.debug('updateObj:', updateObjects);
      if (updateObjects !== []) {
        _ref2 = Object.keys(updateObjects);
        for (_k = 0, _len = _ref2.length; _k < _len; _k++) {
          i = _ref2[_k];
          this.gridObjects[i].setContent(updateObjects[i]);
          this.gridObjects["" + cellX + "," + cellY].setContent(data);
        }
      }
      return window.gApp.gridCanvas.updateCanvas(this.gridObjects);
    };

    Grid.prototype.checkObjectDestroy = function(object, place) {
      var checkObj, h, largeObjectH, largeObjectW, largeObjectX, largeObjectY, tmpObjects, w, _i, _j, _ref, _ref1;
      tmpObjects = [];
      checkObj = this.gridObjects["" + place.x + "," + place.y].object.content[0];
      if (checkObj.type === 'Extender' || checkObj.size.h > 1 || checkObj.size.w > 1) {
        if (checkObj.type === 'Extender') {
          largeObjectX = this.gridObjects["" + place.x + "," + place.y].object.content[0].belongsTo[0];
          largeObjectY = this.gridObjects["" + place.x + "," + place.y].object.content[0].belongsTo[1];
        } else {
          largeObjectY = cellY;
          largeObjectX = cellX;
        }
        largeObjectW = this.gridObjects["" + largeObjectX + "," + largeObjectY].object.content[0].size.w;
        largeObjectH = this.gridObjects["" + largeObjectX + "," + largeObjectY].object.content[0].size.h;
        for (w = _i = largeObjectX, _ref = largeObjectX + largeObjectW - 1; largeObjectX <= _ref ? _i <= _ref : _i >= _ref; w = largeObjectX <= _ref ? ++_i : --_i) {
          for (h = _j = largeObjectY, _ref1 = largeObjectY + largeObjectH - 1; largeObjectY <= _ref1 ? _j <= _ref1 : _j >= _ref1; h = largeObjectY <= _ref1 ? ++_j : --_j) {
            tmpObjects["" + w + "," + h] = {};
          }
        }
      }
      return tmpObjects;
    };

    Grid.prototype.checkObjectBuild = function(object, place) {
      var extender, h, i, tmpObjects, w, _i, _j, _k, _ref, _ref1;
      tmpObjects = [];
      if (object.size.w <= 1 && object.size.h <= 1) {
        if ((place.object.terrain || place.object.terrainable) && (object.terrainable || object.terrain)) {
          tmpObjects["" + place.x + "," + place.y] = object;
        }
        if ((place.object.transporter || place.object.transportable) && object.transportable) {
          tmpObjects["" + place.x + "," + place.y] = object;
        }
      }
      if (object.size.w > 1 || object.size.h > 1) {
        for (w = _i = 0, _ref = object.size.w - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; w = 0 <= _ref ? ++_i : --_i) {
          for (h = _j = 0, _ref1 = object.size.h - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; h = 0 <= _ref1 ? ++_j : --_j) {
            for (i = _k = 0; _k <= 3; i = ++_k) {
              if ((this.gridObjects["" + (place.x + w) + "," + (place.y + h)] == null) || this.gridObjects["" + (place.x + w) + "," + (place.y + h)].object.type !== 'Terrain' || this.gridObjects["" + (place.x + w) + "," + (place.y + h)].object.content[i].type !== void 0) {
                return [];
              }
            }
            extender = {
              'belongsTo': [place.x, place.y],
              'color': object.color,
              'type': 'Extender'
            };
            tmpObjects["" + (place.x + w) + "," + (place.y + h)] = extender;
          }
        }
      }
      return tmpObjects;
    };

    return Grid;

  })();

  GridCanvas = (function() {

    function GridCanvas() {
      this.displayWidth = 7;
      this.displayHeight = 7;
      this.viewPortX = 0;
      this.viewPortY = 0;
      this.redrawAfterScale = false;
    }

    GridCanvas.prototype.drawDisplayedGrid = function(gridObjects) {
      var h, w, _i, _j, _ref, _ref1, _ref2, _ref3;
      for (h = _i = _ref = this.viewPortY, _ref1 = this.viewPortY + this.displayHeight; _ref <= _ref1 ? _i <= _ref1 : _i >= _ref1; h = _ref <= _ref1 ? ++_i : --_i) {
        for (w = _j = _ref2 = this.viewPortX, _ref3 = this.viewPortX + this.displayWidth; _ref2 <= _ref3 ? _j <= _ref3 : _j >= _ref3; w = _ref2 <= _ref3 ? ++_j : --_j) {
          if (gridObjects["" + w + "," + h] != null) {
            if (gridObjects["" + w + "," + h].hasChanged || this.redrawAfterScale) {
              this.updateObject(gridObjects["" + w + "," + h]);
              gridObjects["" + w + "," + h].hasChanged = false;
            }
          }
        }
      }
      return this.redrawAfterScale = false;
    };

    GridCanvas.prototype.drawGridLines = function(ctx, grid) {
      var lineNumX, lineNumY, lineXEnd, lineXStart, lineYEnd, lineYStart, _i, _j, _ref, _ref1, _results;
      ctx.fillStyle = grid.lineColor;
      for (lineNumX = _i = 0, _ref = grid.getRealWidth(); 0 <= _ref ? _i <= _ref : _i >= _ref; lineNumX = 0 <= _ref ? ++_i : --_i) {
        lineXStart = lineNumX * grid.cellSize;
        lineXEnd = lineXStart;
        lineYStart = 0;
        lineYEnd = grid.getHeightPx();
        ctx.beginPath();
        ctx.moveTo(lineXStart, lineYStart);
        ctx.lineTo(lineXEnd, lineYEnd);
        ctx.closePath();
        ctx.stroke();
      }
      _results = [];
      for (lineNumY = _j = 0, _ref1 = grid.getRealWidth(); 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; lineNumY = 0 <= _ref1 ? ++_j : --_j) {
        lineXStart = 0;
        lineXEnd = grid.getWidthPx();
        lineYStart = lineNumY * grid.cellSize;
        lineYEnd = lineYStart;
        ctx.beginPath();
        ctx.moveTo(lineXStart, lineYStart);
        ctx.lineTo(lineXEnd, lineYEnd);
        ctx.closePath();
        _results.push(ctx.stroke());
      }
      return _results;
    };

    GridCanvas.prototype.updateCell = function(ctx, cellX, cellY, cellSize, color) {
      if (color === void 0) {
        color = 'rgba(150,150,150,1)';
      }
      ctx.fillStyle = color;
      ctx.fillRect(cellX * window.gApp.grid.cellSize, cellY * window.gApp.grid.cellSize, cellSize, cellSize);
      ctx.fill();
      return ctx.stroke();
    };

    GridCanvas.prototype.objectCanBePlaced = function(object) {};

    GridCanvas.prototype.updateObject = function(object) {
      var i, _i, _len, _ref, _results;
      _ref = object.getUpdateCoords();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        if (i.icon != null) {
          _results.push(window.gApp.CCanvas.loadImageFromFile(window.gApp.CCanvas.getContext(), i.icon, i.x * window.gApp.grid.cellSize, i.y * window.gApp.grid.cellSize, object.getSize() * window.gApp.grid.cellSize, object.getSize() * window.gApp.grid.cellSize));
        } else {
          _results.push(this.updateCell(window.gApp.CCanvas.getContext(), i.x, i.y, object.getSize() * window.gApp.grid.cellSize, i.color));
        }
      }
      return _results;
    };

    GridCanvas.prototype.updateCanvas = function(gridObjects) {
      var x, y, _i, _j, _ref, _ref1;
      this.drawDisplayedGrid(gridObjects);
      return;
      for (x = _i = 0, _ref = window.gApp.grid.getRealWidth(); 0 <= _ref ? _i <= _ref : _i >= _ref; x = 0 <= _ref ? ++_i : --_i) {
        for (y = _j = 0, _ref1 = window.gApp.grid.getRealHeight(); 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
          if (gridObjects["" + x + "," + y].hasChanged || this.redrawAfterScale) {
            window.gApp.gridCanvas.updateObject(gridObjects["" + x + "," + y]);
            gridObjects["" + x + "," + y].hasChanged = false;
          }
        }
      }
      return this.redrawAfterScale = false;
    };

    return GridCanvas;

  })();

  CCanvas = (function() {

    function CCanvas() {}

    CCanvas.prototype.setCanvas = function(canvasId) {
      this.canvasId = canvasId;
      this.canvas = document.getElementById(this.canvasId);
      this.canvas.onmousedown = this.canvasDown;
      this.canvas.onmouseup = this.canvasUp;
      return this.ctx = this.canvas.getContext('2d');
    };

    CCanvas.prototype.getCanvas = function() {
      return this.canvas;
    };

    CCanvas.prototype.getContext = function() {
      return this.ctx;
    };

    CCanvas.prototype.canvasDown = function(e) {
      return this.clickDown = {
        'x': e.pageX - e.srcElement.offsetLeft,
        'y': e.pageY - e.srcElement.offsetTop
      };
    };

    CCanvas.prototype.canvasUp = function(e) {
      var canvas, x, y;
      canvas = e.srcElement;
      x = e.pageX - canvas.offsetLeft;
      y = e.pageY - canvas.offsetTop;
      if (x === this.clickDown['x'] && y === this.clickDown['y']) {
        return EventedClass.trigger('cgrid_click', [x, y, canvas.id]);
      } else {
        return EventedClass.trigger('cgrid_drag', [
          this.clickDown, {
            'x': x,
            'y': y
          }, canvas.id
        ]);
      }
    };

    CCanvas.prototype.loadImageFromFile = function(ctx, fileName, x, y, w, h) {
      var img;
      img = new Image();
      img.src = fileName;
      return ctx.drawImage(img, 7, 7, w, h, x, y, w, h);
    };

    return CCanvas;

  })();

  window.EventedClass = EventedClass = (function() {

    function EventedClass() {}

    EventedClass.prototype.bind = function(event, callback) {
      this.eventHandlers || (this.eventHandlers = {});
      if (this.eventHandlers[event] == null) {
        this.eventHandlers[event] = [];
      }
      this.eventHandlers[event].push(callback);
      return true;
    };

    EventedClass.prototype.unbind = function(event, callback) {
      this.eventHandlers || (this.eventHandlers = {});
      if ((this.eventHandlers[event] != null) && this.eventHandlers[event].indexOf(callback) >= 0) {
        this.eventHandlers[event].splice(this.eventHandlers[event].indexOf(callback), 1);
        return true;
      } else {
        return false;
      }
    };

    EventedClass.prototype.unbindAll = function() {
      this.eventHandlers = {};
      return true;
    };

    EventedClass.prototype.trigger = function(event, data) {
      var callback, _i, _len, _ref;
      if (data == null) {
        data = {};
      }
      this.eventHandlers || (this.eventHandlers = {});
      if ((this.eventHandlers[event] != null) && this.eventHandlers[event].length > 0) {
        _ref = this.eventHandlers[event];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          callback = _ref[_i];
          if (typeof callback === 'function') {
            callback(data);
          }
        }
        return true;
      } else {
        return false;
      }
    };

    return EventedClass;

  })();

  Function.prototype.property = function(prop, desc) {
    return Object.defineProperty(this.prototype, prop, desc);
  };

  ObjectFactory = (function() {

    function ObjectFactory() {}

    ObjectFactory.getClass = function(cName) {
      switch (cName) {
        case 'Terrain':
          return new ObjectTerrain;
        case 'Transporter':
          return new ObjectTransporter;
        case 'Extender':
          return new ObjectExtender;
        default:
          return new ObjectGeneric;
      }
    };

    return ObjectFactory;

  })();

  ObjectContainer = (function() {

    function ObjectContainer(object) {
      this.object = object;
      this.hasChanged = false;
    }

    ObjectContainer.property('size', {
      get: function() {
        return this.object.size;
      },
      set: function(s) {
        return this.object.size = s;
      }
    });

    ObjectContainer.prototype.setContent = function(d) {
      var setContent, _ref;
      if (d.type === 'destroy') {
        return;
      }
      setContent = true;
      if ((_ref = d.type) === 'Terrain' || _ref === 'Transporter') {
        setContent = false;
        this.object = ObjectFactory.getClass(d.type);
        this.updateNewObject();
      }
      if (setContent) {
        this.object.setContent(d);
      }
      return this.hasChanged = true;
    };

    ObjectContainer.prototype.updateNewObject = function() {
      this.setX(this.x);
      return this.setY(this.y);
    };

    ObjectContainer.prototype.getUpdateCoords = function() {
      return this.object.getUpdateCoords();
    };

    ObjectContainer.prototype.getSize = function() {
      return this.object.size;
    };

    ObjectContainer.prototype.setX = function(x) {
      this.x = x;
      return this.object.x = this.x;
    };

    ObjectContainer.prototype.setY = function(y) {
      this.y = y;
      return this.object.y = this.y;
    };

    return ObjectContainer;

  })();

  ObjectGeneric = (function() {
    "takes whole grid cell, contains no other objects";
    function ObjectGeneric() {
      this.direction = 'l2r';
      this.size = 1;
      this.content = [{}, {}, {}, {}];
    }

    ObjectGeneric.prototype.setContent = function(d) {
      return extend(this.content, d);
    };

    ObjectGeneric.prototype.getUpdateCoords = function() {
      return [
        {
          'x': this.x,
          'y': this.y,
          'color': this.content[0].color
        }
      ];
    };

    ObjectGeneric.prototype.setType = function(type) {
      this.type = type;
    };

    ObjectGeneric.prototype.getType = function() {
      return this.type;
    };

    return ObjectGeneric;

  })();

  ObjectExtender = (function(_super) {

    __extends(ObjectExtender, _super);

    "For multi-cell objects";

    function ObjectExtender() {
      return ObjectExtender.__super__.constructor.apply(this, arguments);
    }

    ObjectExtender.prototype.setContent = function(content) {
      this.content = content;
      return console.log('ObjExtender.setContent - Not implemented');
    };

    return ObjectExtender;

  })(ObjectGeneric);

  ObjectMulti = (function(_super) {

    __extends(ObjectMulti, _super);

    function ObjectMulti() {
      ObjectMulti.__super__.constructor.apply(this, arguments);
      this.direction = 'l2r';
      this.size = 0.5;
      this.directionDict = {
        'lefttop': 0,
        'leftbottom': 2,
        'righttop': 1,
        'rightbottom': 3
      };
    }

    ObjectMulti.prototype.resetContent = function() {
      return this.content = [{}, {}, {}, {}];
    };

    ObjectMulti.prototype.getUpdateCoords = function() {
      return [
        {
          'x': this.x,
          'y': this.y,
          'color': this.content[0].color,
          'image': this.content[0].image,
          'icon': this.content[0].icon
        }, {
          'x': this.x + 0.5,
          'y': this.y,
          'color': this.content[1].color,
          'image': this.content[1].image,
          'icon': this.content[1].icon
        }, {
          'x': this.x,
          'y': this.y + 0.5,
          'color': this.content[2].color,
          'image': this.content[2].image,
          'icon': this.content[2].icon
        }, {
          'x': this.x + 0.5,
          'y': this.y + 0.5,
          'color': this.content[3].color,
          'image': this.content[3].image,
          'icon': this.content[3].icon
        }
      ];
    };

    ObjectMulti.prototype.setContent = function(content) {
      var dictKey;
      dictKey = 0;
      if (content.direction != null) {
        dictKey = this.directionDict[content.direction];
      }
      this.content[dictKey] = content;
    };

    return ObjectMulti;

  })(ObjectGeneric);

  ObjectTerrain = (function(_super) {

    __extends(ObjectTerrain, _super);

    "takes whole grid cell, is a container";

    function ObjectTerrain() {
      ObjectTerrain.__super__.constructor.apply(this, arguments);
      this.content[0].color = 'rgba(30,90,170,1)';
      this.content[1].color = 'rgba(30,90,170,1)';
      this.content[2].color = 'rgba(30,90,170,1)';
      this.content[3].color = 'rgba(30,90,170,1)';
      this.terrain = true;
      this.type = 'Terrain';
    }

    ObjectTerrain.prototype.setContent = function(d) {
      ObjectTerrain.__super__.setContent.apply(this, arguments);
      if (d.type === this.type) {
        console.log('erasing terrain content');
        return this.resetContent;
      }
    };

    return ObjectTerrain;

  })(ObjectMulti);

  ObjectTransporter = (function(_super) {

    __extends(ObjectTransporter, _super);

    "takes whole grid cell, is a container, rotatable";

    function ObjectTransporter() {
      ObjectTransporter.__super__.constructor.apply(this, arguments);
      this.transporter = true;
      this.terrainable = true;
      this.type = 'Transporter';
      this.image = 'img/entity/basic-transport-belt/basic-transport-belt.png';
      this.icon = 'img/icons/basic-transport-belt/basic-transport-belt.png';
    }

    ObjectTransporter.prototype.rotateItem = function() {
      return this.content.color = [this.content.color[3], this.content.color[1], this.content.color[4], this.content.color[2]];
    };

    return ObjectTransporter;

  })(ObjectMulti);

  EventedClass = new EventedClass();

  EventedClass.bind('cgrid_click', function(e) {
    var cellX, cellY, obj, qX, qY, quX, quY, updX, updY, _ref;
    cellX = Math.floor(e[0] / window.gApp.grid.cellSize);
    cellY = Math.floor(e[1] / window.gApp.grid.cellSize);
    qX = e[0] - cellX * window.gApp.grid.cellSize;
    qY = e[1] - cellY * window.gApp.grid.cellSize;
    if (qX <= (cellX + 0.5 * window.gApp.grid.cellSize)) {
      quX = 'left';
      updX = cellX;
    } else {
      quX = 'right';
      updX = cellX + 0.5;
    }
    if (qY <= (cellY + 0.5 * window.gApp.grid.cellSize)) {
      quY = 'top';
      updY = cellY;
    } else {
      quY = 'bottom';
      updY = cellY + 0.5;
    }
    if (angular.element('#objectsPanel').scope().selectedObject === 'undefined') {
      return;
    }
    obj = angular.element('#objectsPanel').scope().selectedObject;
    if ((_ref = obj.type) !== 'Terrain' && _ref !== 'Transporter' && _ref !== 'Factory') {
      obj.direction = quX + quY;
    } else {
      obj.direction = 'lefttop';
    }
    obj.size = {
      'w': obj.w,
      'h': obj.h
    };
    console.debug('obj for update', obj, 'direction:', obj.direction);
    return window.gApp.grid.updateCellContainer(cellX, cellY, obj);
  });

  $(document).ready(function() {
    window.gApp = new App();
    window.dGrid = new window.debugGrid();
    $('#zoom_in').bind('click', window.gApp.grid.scaleDown);
    return $('#zoom_out').bind('click', window.gApp.grid.scaleUp);
  });

  ({
    SimpleController: function($scope) {
      return $scope.names = ['Dave', 'Napur', 'Heedy', 'Shriva'];
    }
  });

}).call(this);
